Logging change
Transport-for-the-North/caf.space pull request #11
Opened 2023-08-01 14:15 UTC by isaac-tfn

Describe Changes
---

Task Checklist
----
- [ ] Have unittests been added (testing individual functions and their edge cases)
- [ ] Have integration tests been added (if applicable, to test modules of functionality)
- [ ] Updated RELEASE.md to reflect changes in PR
- [ ] Have new dependencies been added?
  - [ ] Have they been added to either `requirements.txt` or `requirements_dev.txt`.
  - [ ] Have they been added to `setup.cfg`

2023-08-02 15:44 UTC, wsp-mbuckley requested changes
Looks like you've implemented LogHelper correctly, the only thing is I would use `__package__` for the root logger instead of `"SPACE"`, this would mean you can use `LOG = logging.getLogger(__name__)` in all the modules like you have used in 'inputs.py'.

Also, when you're in the `NotebookApp._redirect_logging` function you're adding to the root logger but not to the Python warnings logger ("py.warnings") which means Python warnings won't show up in your GUI but will show up in the console window and the log file.

I think a new `add_handler` method should be added to `LogHelper` in `caf.toolkit`, which adds handlers to the root logger and warning logger and can be used by other people.

2023-08-02 15:44 UTC, wsp-mbuckley commented on src/caf/space/__main__.py
> +    with LogHelper("SPACE", details, log_file=log_out / "SPACE.log"):
Use `__package__` for the root logger (which will be 'caf.space').

```suggestion
    with LogHelper(__package__, details, log_file=log_out / "SPACE.log"):
```

2023-08-02 15:44 UTC, wsp-mbuckley commented on src/caf/space/ui.py
> +        self.logger = logging.getLogger("SPACE")
Use `__package__` which will be 'caf.space'

```suggestion
        self.logger = logging.getLogger(__package__)
```

2023-08-02 15:44 UTC, wsp-mbuckley commented on src/caf/space/ui.py
>          self.logger.setLevel(logging.DEBUG)
Get the `__package__` logger to be consistent

```suggestion
        self.logger = logging.getLogger(__package__)
        self.logger.setLevel(logging.DEBUG)
```

2023-08-02 15:44 UTC, wsp-mbuckley commented on src/caf/space/ui.py
>          self.console_handler.setFormatter(fmt)
Use `__package__` instead of `"SPACE"` on line 794 above this

2023-10-10 08:42 UTC, isaac-tfn commented
@wsp-mbuckley I only just remembered the suggested changes in this review, could you take a quick 5 min look and (hopefully) approve?

2023-10-10 09:50 UTC, wsp-mbuckley commented
> @wsp-mbuckley I only just remembered the suggested changes in this review, could you take a quick 5 min look and (hopefully) approve?

There were 3 comments where I said use `__package__` instead of "SPACE" for the `getLogger` functions which haven't been changed yet, please could you do those. I think everything else looks good

2023-10-10 09:52 UTC, isaac-tfn commented
> > @wsp-mbuckley I only just remembered the suggested changes in this review, could you take a quick 5 min look and (hopefully) approve?
> 
> There were 3 comments where I said use `__package__` instead of "SPACE" for the `getLogger` functions which haven't been changed yet, please could you do those. I think everything else looks good

I thought I'd changed them - I'll make sure I've pushed all my changes sorry

2023-10-10 10:02 UTC, isaac-tfn commented
@wsp-mbuckley I might be missing something but I see 4 places you've requested "SPACE" changes to __package__ and I've made those changes. All of the instances seem to be in 'ui' and '__main__' so if there are more places it needs changing I don't think I can see those comments

2023-10-10 10:08 UTC, wsp-mbuckley approved these changes

2023-10-10 10:14 UTC, isaac-tfn commented
> > @wsp-mbuckley I might be missing something but I see 4 places you've requested "SPACE" changes to **package** and I've made those changes. All of the instances seem to be in 'ui' and '**main**' so if there are more places it needs changing I don't think I can see those comments
> 
> Sorry Isaac, you're right when I looked at the comments in VS code it linked back to the state of the file at the commit when I made the comment (I guess trying to be helpful?)

No problem - I think suggestions is relatively new? (or you and Ben have both found the feature at about the same time) so maybe not quite optimised in VS code. Thanks for the review will merge now.

2023-10-10 10:14 UTC, merged